url: http://www.takefiveinteractive.com
baseurl:

# Site settings
title: TakeFive Interactive
email: xiaohang@takefiveinteractive.com
description: "We are a group of five motivated individuals based in UIUC"

# Exclude additional directories
exclude: ['ZhihuFont/*']

# Minifier settings
jekyll-press:
  # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  exclude: []
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kedan Li
  pic: kedan
  position: Lead iOS, Product Artisan
  social:
    - title: github
      url: https://github.com/likedan
    - title: zhihu
      url: http://www.zhihu.com/people/kedan-li
    - title: linkedin
      url: https://www.linkedin.com/in/kedanli

- name: Yu Wang
  pic: yu
  position: iOS Developer, UI/UX
  social:
    - title: github
      url: https://github.com/yuwang17
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100007201530170
    - title: linkedin
      url: https://www.linkedin.com/in/wangyu2165

- name: Suji Yan
  pic: ted
  position: Frontend, Design
  social:
    - title: github
      url: http://github.com/Tedko
    - title: zhihu
      url: http://www.zhihu.com/people/suji-yan
    - title: linkedin
      url: https://www.linkedin.com/in/tedkoyan

- name: Mike Zhao
  pic: mike
  position: iOS Developer
  social:
    - title: github
      url: https://github.com/DeRedBaron

- name: Yifei Teng
  pic: yifei
  position: Backend, DevOps
  social:
    - title: github
      url: https://github.com/tengyifei
    - title: link
      url: https://thinkingandcomputing.com
    - title: linkedin
      url: https://www.linkedin.com/in/yifeiteng

- name: Xiaohang Yu
  pic: lafickens
  position: Backend, Infrastructure, Android
  social:
    - title: github
      url: https://github.com/lafickens
    - title: facebook
      url: https://facebook.com/lafickens
    - title: linkedin
      url: https://www.linkedin.com/in/yuxiaohang

- name: Zhongzhi Yu
  pic: c4phone
  position: Backend, Android
  social:
    - title: github
      url: https://github.com/C4Phone
    - title: link
      url: http://normal-cforphone.blogspot.com/
    - title: google-plus
      url: https://plus.google.com/101206478784989285519/posts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/TakeFiveInteractive

# Postal address (add as many lines as necessary)
address:
  - line: URH Wardall, 1012 W. Illinois St.
  - line: Urbana, IL 61801

# Build settings
markdown: kramdown
permalink: pretty
