url: http://www.takefiveinteractive.com
baseurl:

# Site settings
title: TakeFive Interactive
email: xiaohang.yu@takefiveinteractive.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kedan Li
  pic: 1
  position: Frontend (iOS/UI/UX)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Yu Wang
  pic: 5
  position: Frontend (iOS/UI/UX)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Suji Yan
  pic: 4
  position: Frontend, Material Design
  social:
    - title: github
      url: "http://github.com/Tedko"
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Yifei Teng
  pic: 2
  position: Backend
  social:
    - title: github
      url: https://github.com/tengyifei
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Xiaohang Yu
  pic: 3
  position: Backend
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/TakeFiveInteractive

# Postal address (add as many lines as necessary)
address:
  - line: URH Wardall, 1012 W. Illinois St.
  - line: Urbana, IL 61801

# Build settings
markdown: kramdown
permalink: pretty
